ren it.txt txt.it
ren itpcreate.qrpglesrc qrpglesrc.itpcreate
ren itpdelete.qrpglesrc qrpglesrc.itpdelete
ren itpkeyupdd.qddssrc qddssrc.itpkeyupdd
ren itpprgkeyd.qddssrc qddssrc.itpprgkeyd
ren itpprgkeyr.qrpglesrc qrpglesrc.itpprgkeyr
ren itpprgmnud.qddssrc qddssrc.itpprgmnud
ren itpprgmnur.qrpglesrc qrpglesrc.itpprgmnur
ren itpprgupdd.qddssrc qddssrc.itpprgupdd
ren itpprgupdr.qrpglesrc qrpglesrc.itpprgupdr
ren itppurge.qcllesrc qcllesrc.itppurge
ren itppurge.qcmdsrc qcmdsrc.itppurge
ren itppurgel1.qddssrc qddssrc.itppurgel1
ren itppurgel2.qddssrc qddssrc.itppurgel2
ren itppurgep.qddssrc qddssrc.itppurgep
ren itppurger.qrpglesrc qrpglesrc.itppurger
ren itppurgev.qcllesrc qcllesrc.itppurgev
ren itppurkey.qddssrc qddssrc.itppurkey
ren itppurkey1.qddssrc qddssrc.itppurkey1
ren itppurkey2.qddssrc qddssrc.itppurkey2
ren itpreseqcl.qcllesrc qcllesrc.itpreseqcl
ren itpreseqr.qrpglesrc qrpglesrc.itpreseqr
ren itprestore.qcllesrc qcllesrc.itprestore
ren itprestore.qcmdsrc qcmdsrc.itprestore
ren itprestorr.qrpglesrc qrpglesrc.itprestorr
ren itprestorv.qcllesrc qcllesrc.itprestorv
ren itpshare.qcpysrc qcpysrc.itpshare
ren itpshare.qrpglesrc qrpglesrc.itpshare
ren itpstsset.qrpglesrc qrpglesrc.itpstsset
